[project]
name = "tidytuesday"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "madl1900", email = "lou24011@byui.edu" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
tidytuesday = "tidytuesday:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
